import Head from 'next/head'
import { sanityClient, urlFor } from "../sanity";
import Image from 'next/image'
import Navbar from '../components/Homepage/Navbar/Navbar'
import HeroSection from '../components/Homepage/HeroSection/HeroSection'
import HeroImage from '../components/Homepage/HeroImage/HeroImage'
import OurTools from '../components/Homepage/OurTools/OurTools';
import Service from '../components/Homepage/Service/Service';
import CompleteSEO from '../components/Homepage/CompleteSEO/CompleteSEO';
import Testimonials from '../components/Homepage/Testimonials/Testimonials';
import CompanyStar from '../components/Homepage/CompanyStar/CompanyStar';
import Footer from '../components/Homepage/Footer/Footer';

const section1Query = `*[_type == "firstSection"]{
  name, userImage, referenceList,
}`;
const section2Query = `*[_type == "secondSection"]{
  name, userImage, company, position, quote,
}`;
const section3Query = `*[_type == "gridOne"]{
  title, userImage, slogan, bullet1, bullet2, bullet3, bullet4,
}`;
const section4Query = `*[_type == "testimonial"]{
  name, userImage, position, quote,
}`;

const section5Query = `*[_type == "star"]{
  name, userImage, referenceList,
}`;

export default function Home({ section1, section2, section3, section4, section5 }) {
  return (
    <div>
      <Head>
        <title>Bright Local SEO | Sanity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/* components */}
      <Navbar />
      <HeroSection />
      <HeroImage section1={section1} /> 
      <OurTools section2={section2} /> 
      <Service section3={section3} />    
      <CompleteSEO />
      <Testimonials section4={section4} />
      <CompanyStar section5={section5}/>
      <Footer />
    </div>
  )
}

export async function getStaticProps() {
  const section1 = await sanityClient.fetch(section1Query,);
  const section2 = await sanityClient.fetch(section2Query,);
  const section3 = await sanityClient.fetch(section3Query,);
  const section4 = await sanityClient.fetch(section4Query,);
  const section5 = await sanityClient.fetch(section5Query,);
  
  return { props: { section1, section2, section3, section4, section5} };
}
